### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dfmjndm** [azmiao/mc_status#1]
旧版用的好好的，更新之后就不能用了
bot发送：查询失败！错误明细：[Errno 111] Connection refused
控制台：
/usr/local/lib/python3.9/site-packages/mcstatus/utils.py:104: DeprecationWarning: 'MinecraftServer' is deprecated and is expected to be removed on 2022-08, use 'JavaServer' instead.
  warnings.warn(warn_message, category=DeprecationWarning)

看起来是要我用java服务器，但是这本来就是java服务器

**Comment by dfmjndm** [comment]
udp，tcp开着的，query端口也开着的

**Comment by azmiao** [comment]
这个warning是正常现象，暂时不用管，依赖后续会修复的，当然如果你不想看到这个，可以将依赖回退旧版本，比如6.5.0.
另外connected refused就是你端口什么的没开好，链接不到端口，请确保防火墙和安全组都放行了端口

**Comment by azmiao** [comment]
不行的话要不把25567的UDP和TCP也全打开试试

**Comment by azmiao** [comment]
我自己这里的话端口就只开了服务器上的 25565 TCP / UDP 和 安全组的 25565 TCP / UDP

**Comment by dfmjndm** [comment]
都试过了，没有用，还是connecting refused，而且如果是端口问题我旧版是可以正常使用的

**Comment by int-PP** [comment]
我这也出问题了
![WD$XN4L~WJZC)IAL {`V5VN](https://user-images.githubusercontent.com/105854929/172424594-65bd74ea-3e2d-4b97-99f8-d36bd841ff69.png)
，显示 查询失败！错误明细：[WinError 10054] [远程主机强迫关闭了一个现有的连接。 端口和query查询功能也开了
![U_9P}B 88R)XQ20F6( 5(FG](https://user-images.githubusercontent.com/105854929/172424330-71e39505-7407-4a55-bec1-38b80f05cd71.png)

**Comment by azmiao** [comment]
> 我这也出问题了 ![WD$XN4L~WJZC)IAL {`V5VN](https://user-images.githubusercontent.com/105854929/172424594-65bd74ea-3e2d-4b97-99f8-d36bd841ff69.png) ，显示 查询失败！错误明细：[WinError 10054] [远程主机强迫关闭了一个现有的连接。 端口和query查询功能也开了 ![U_9P}B 88R)XQ20F6( 5(FG](https://user-images.githubusercontent.com/105854929/172424330-71e39505-7407-4a55-bec1-38b80f05cd71.png) ![InkedYPRLCQN50ADLA1AK7U5ET{O_LI](https://user-images.githubusercontent.com/105854929/172425982-6c893f6e-e7a9-4cba-803d-dff2d48e5e4c.jpg)

一般来说，10054就是连不上服务器的这个端口，只要开启查询功能后，一般来说服务器防火墙和服务器安全组都开放端口就行的，但如果端口都放行了，配置文件也正常了还连不上我也就不知道咋回事了，我的几台服务器和群友的几个服务器也都能查的到，还是建议自己检查一下配置文件后面有没有冲突，或者防火墙和安全组的端口都放行了

**Comment by int-PP** [comment]
> > 我这也问题了![WD$XN4L~WJZC)IAL {`V5VN](https://user-images.githubusercontent.com/105854929/172424594-65bd74ea-3e2d-4b97-99f8-d36bd841ff69.png)，查询失败！错误提示：[WinError 10054] [远程主机已经关闭了一个现有的连接功能。![U_9P}B 88R)XQ20F6( 5(FG](https://user-images.githubusercontent.com/105854929/172424330-71e39505-7407-4a55-bec1-38b80f05cd71.png) ![InkedYPRLCQN50ADLA1AK7U5ET{O_LI](https://user-images.githubusercontent.com/105854929/172425982-6c893f6e-e7a9-4cba-803d-dff2d48e5e4c.jpg)
> 
> 1005410054，只要不连上这个端口的安全端口，只要有查询功能，一般来说服务器防火墙和服务器都可以正常运行，但如果配置都行了，配置文件也正常了，还连不上我不知道你自己配置，我的朋友的几个服务器都可以自己检查一下，或者建议检查文件后面没有一些故障，或者台上的防火墙和安全组的端口都可以放行了

现在换了个端口，一会能查一会查不了，感觉是我服务器设置错了啥
![GI)IS`G`3P( G3K%ZIET9}6](https://user-images.githubusercontent.com/105854929/172514271-b3e57d88-97de-4f92-8d42-f5b28f313c76.jpg)
建议大佬增加个域名解析IP

**Comment by azmiao** [comment]
> 

现在域名可能能查了，你更新试试，我还没空测试，另外一会能查一会不能查那不能查显示的错误是timeout还是10054，如果10054那我也不知道了，timeout一般只是偶尔没连上服务器，正常的。

**Comment by int-PP** [comment]
> > 
> 
> 现在域名可能能查了，你更新试试，我还没空测试，另外一会能查一会不能查那不能查显示的错误是timeout还是10054，如果10054那我也不知道了，timeout一般只是偶尔没连上服务器，正常的。

好的，谢谢大佬

**Comment by int-PP** [comment]
> > 
> 
> 现在域名可能能查了，你更新试试，我还没空测试，另外一会能查一会不能查那不能查显示的错误是timeout还是10054，如果10054那我也不知道了，timeout一般只是偶尔没连上服务器，正常的。

![(@{QIH_9O9PVQIHR~BFG48L](https://user-images.githubusercontent.com/105854929/172546038-6f45e13c-d6ce-4890-addb-6c67c80dd326.png)出错没办法用了现在

**Comment by azmiao** [comment]
> > > 
> > 
> > 
> > 现在域名可能能查了，你更新试试，我还没空测试，另外一会能查一会不能查那不能查显示的错误是timeout还是10054，如果10054那我也不知道了，timeout一般只是偶尔没连上服务器，正常的。
> 
> ![(@{QIH_9O9PVQIHR~BFG48L](https://user-images.githubusercontent.com/105854929/172546038-6f45e13c-d6ce-4890-addb-6c67c80dd326.png)出错没办法用了现在

哦，我改错了2333，你现在再试试

**Comment by int-PP** [comment]
> > > > 
> > > 
> > > 
> > > 现在域名可能能查了，你更新试试，我还没空测试，另外一会能查一会不能查那不能查显示的错误是timeout还是10054，如果10054那我也不知道了，timeout一般只是偶尔没连上服务器，正常的。
> > 
> > 
> > ![(@{QIH_9O9PVQIHR~BFG48L](https://user-images.githubusercontent.com/105854929/172546038-6f45e13c-d6ce-4890-addb-6c67c80dd326.png)出错没办法用了现在
> 
> 哦，我改错了2333，你现在再试试

可以用了！
![P$SL7W3V`O9LAE3(19M56PT](https://user-images.githubusercontent.com/105854929/172579654-b5c80452-71af-491f-bbc6-a073426efa91.jpg)

**Comment by int-PP** [comment]
又出了点小问题，绑定了ip之后，使用mc数据命令没反应，hoshino窗口也没看到响应
![image](https://user-images.githubusercontent.com/105854929/172967082-b66e1f3e-9b0a-40ea-96c8-94235037ff37.png)

**Comment by int-PP** [comment]
> > 又出了点小问题，绑定了ip之后，使用mc数据命令没反应，hoshino窗口也没看到响应 ![image](https://user-images.githubusercontent.com/105854929/172967082-b66e1f3e-9b0a-40ea-96c8-94235037ff37.png)
> 
> 哦，抱歉，现在应该好了，最近忙，正则改的没注意到23333

可以了
![SRVR PH(T4Y %_Z{AUUS63H](https://user-images.githubusercontent.com/105854929/172977583-24764abf-6ca0-48db-bc41-93add63202ca.png)
