### ISSUE TITLE
不提醒服务器人员变动

### ISSUE THREAD

**Issue by ElizaKzi** [azmiao/mc_status#2]
![image](https://user-images.githubusercontent.com/63360445/178938141-972242fd-8703-4efa-91c6-b4878912157f.png)
![image](https://user-images.githubusercontent.com/63360445/178938247-64bc5c83-08f5-48cb-b88a-e28530c48f02.png)
后台是在检测的，我也打开了功能，但是不提醒，这是为什么呢

**Comment by azmiao** [comment]
已修复

**Comment by ElizaKzi** [comment]
> 已修复

可以正常使用了，感谢！
